global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "analytics-service"
    static_configs:
      - targets: ["analytics-service:8083"]
        labels:
          service: "analytics"
    metrics_path: /metrics
