name: CI/CD pipeline

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  # Job 1: Order Service - Build and push to Yandex Container Registry and deploy
  build-and-push-order-service:
    name: Build and push order-service to YC Registry
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./order-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        run: |
          docker build . --file Dockerfile --tag cr.yandex/${{ secrets.YC_REGISTRY_ID }}/order-service:latest

      - name: Login to YC Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}

      - name: Push tag to YC Registry
        run: |
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/order-service:latest

  deploy-order-service:
    name: Deploy order-service to Serverless Container
    runs-on: ubuntu-latest
    needs: [build-and-push-order-service]
    steps:
      - name: Deploy serverless container
        uses: yc-actions/yc-sls-container-deploy@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_KEYS }}
          container-name: order-service
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/order-service:latest
          revision-service-account-id: ${{ secrets.YC_MA_ID }}
          revision-env: |
            POSTGRES_URL=postgresql://secUREusER:StrongEnoughPassword@51.250.26.59:5432/orderdb?sslmode=disable
            REDIS_ADDR=51.250.26.59:6379
            KAFKA_BROKERS=51.250.26.59:9092
            CONFIG_PATH=/config/config.yaml
            SERVER_PORT=8080

  # Job 2: Menu Service - Build and push to DockerHub
  build-and-push-menu-service:
    name: Build and push menu-service to DockerHub
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./menu-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/menu-service:latest

      - name: Push to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/menu-service:latest
