name: CI – Big Bob Pizza

on:
  pull_request:
    branches:
      - main

jobs:
  # =========================
  # ORDER SERVICE
  # =========================
  order-service:
    name: Order Service – Build & Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: order-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run unit tests
        run: make unit-test

      - name: Run integration tests
        run: make integration-test

      - name: Run E2E tests
        run: make e2e-test

